### PR TITLE
stone paper scissor game guided project added

### PR DESCRIPTION
**Pull request by RobertFedred**

### CODE REVIEW

**Review by Pranavtechie — APPROVED** [review]

**Comment by Pranavtechie** [comment]
@RobertFedred Can you improve the design of the project, it seems to be a very bloated right now. Feel free to open a new PR when done with the changes

**Comment by RobertFedred** [comment]
I think the design is accurate for a pc screen.

**Comment by Pranavtechie** [comment]
@RobertFedred The actual is looks very bloated, can you make the UI a bit more elegant

**Comment by Pranavtechie** [comment]
@RobertFedred A simple background or a gradient one would be better

**Pull request closed without merging**
