### PR TITLE
Add pomodoro app

### LINKED ISSUE #108: Pomodoro timer
Hey, I'd like to contribute a [pomodoro time-tracking app](https://en.wikipedia.org/wiki/Pomodoro_Technique) to this project. Please let me know if I can work on this. Thanks

### PR DESCRIPTION
**Pull request by SiddharthShyniben**
Guided project for pomodoro app. Closes #108

### CODE REVIEW

**Review by Pranavtechie — CHANGES_REQUESTED** [review]
Hey @SiddharthShyniben , please update the cover image of the project, 

Please include the necessary assets required for the project in the `/assets` folder of the boilerplate code. 

I also see that the `/designs` folder is missing in the boilerplate code, it is mandatory to have a designs folder and share the final output of the app in desktop and mobile view as well

**Comment by SiddharthShyniben** [comment]
I've pushed the designs to the starter repo and added the cover image.

There are no assets needed for this project, so I haven't created a folder.

**Comment by SiddharthShyniben** [comment]
I've pushed the designs to the starter repo and added the cover image.

No assets are needed for this project, so I haven't created a folder.

**Review by ayushete02 — APPROVED** [review]

**Review by Pranavtechie — APPROVED** [review]

**Comment by Pranavtechie** [comment]
@SiddharthShyniben Please drop your email here or email it to pranav@codedamn.com

**Pull request merged**
