### PR TITLE
Dice game project added

### PR DESCRIPTION
**Pull request by BarmenduC**
A project which builds a two-player, web-based dice game which declares the winner on the basis of highest roll of the dice.

### CODE REVIEW

**Comment by BarmenduC** [comment]
#116

**Comment by Pranavtechie** [comment]
@BarmenduC 

You're missing the `type` key in the `spec.yml` : Please add it 

Please set the cover image: to a raw github link , by uploading the image to the boilerplate repo. Please upload a new cover image that shares the output view of the project. 

Feel free to open a new PR when these changes are done

**Comment by BarmenduC** [comment]
Thanks a lot Pranav for notifying me. I will be making the changes and will
be opening a new PR as soon as possible.

Is there any deadline before which I am supposed to be done with the task?

**Comment by Pranavtechie** [comment]
Hey @BarmenduC , to qualify for the hacktoberfest submission please set it before 13 November 2022

**Pull request closed without merging**
