### PR TITLE
meme generator project added

### PR DESCRIPTION
**Pull request by Utkarsh212**

### CODE REVIEW

**Comment by Pranavtechie** [comment]
Hey @Utkarsh212 , already a meme generator app PR has been submitted. https://github.com/codedamn/projects/pull/56

**Comment by Utkarsh212** [comment]
@Pranavtechie As the Already submitted PR #56 is still not merged. Also, the meme generator project I proposed is based on React.js and CSS, which makes its tech stack different from #56. Adding to that, it is not just a meme generator one can also download the generated meme. In my opinion, this project must be treated as a separate project.

**Review by Pranavtechie — APPROVED** [review]

**Comment by Pranavtechie** [comment]
@Utkarsh212 Please share your email address here, or reach out to me at pranav@codedamn.com

**Comment by Utkarsh212** [comment]
Email Address: utka21200@gmail.com

**Pull request merged**
