### PR TITLE
I have contributed succesfully

### PR DESCRIPTION
**Pull request by Vishal2002**
Please Review my PR and merge it.

### CODE REVIEW

**Comment by Vishal2002** [comment]
Please Review and Merge the PR.

**Comment by Vishal2002** [comment]
Bro, Please merge the PR otherwise it won't be counted under Hacktoberfest 2022.

**Comment by Pranavtechie** [comment]
Hey @Vishal2002 , you were supposed to create a guided project version of the project.

**Comment by Vishal2002** [comment]
Bro, what is a guided project?

**Comment by Pranavtechie** [comment]
Please go through the `Readme.md` for understanding it. You can also go through an existing guided project in codedamn to understand it https://codedamn.com/project/multiverse-html5-photo-gallery

**Pull request closed without merging**
