### PR TITLE
Galaxy library Project Review

### PR DESCRIPTION
**Pull request by Abbhiishek**
This PR is from issue #130 

Tried to follow all the guidelines :). If however missed , let me know will update the branch.

### CODE REVIEW

**Review by Pranavtechie — APPROVED** [review]

**Comment by Abbhiishek** [comment]
🤞

**Comment by Pranavtechie** [comment]
Hey @Abbhiishek , please drop your email address here or you can email it to pranav@codedamn.com

**Comment by Abbhiishek** [comment]
Hey @Pranavtechie 

You can reach out to me here : abhishekkushwaha1479@gmail.com

**Comment by Pranavtechie** [comment]
@Abbhiishek Please add the `designs` and the `assets` folder in the boilerplate repo. They are important folders for a user to build this project

**Pull request merged**
