### PR TITLE
Meetup Project 

### PR DESCRIPTION
**Pull request by Pranavtechie**

### CODE REVIEW

**Review by Pranavtechie — COMMENTED** [review]
@rishabhrao good to go

**Review by rishabhrao — APPROVED** [review]

**Comment by ritik3131** [comment]
Hey @Pranavtechie , @rishabhrao how can I can get Codedamn Merch Kit as this pr is merged in this repo

**Comment by Pranavtechie** [comment]
@ritik3131 Please share your email address here or reach out to me at [pranav@codedamn.com](mailto:pranav@codedamn.com)

**Comment by ritik3131** [comment]
@Pranavtechie, This is my email:- ritikgupta830offical@gmail.com

**Pull request merged**
